#!/bin/sh -xeu

target="$(realpath -- "$1")"

: "${dry_run=}"

_not_dry() {
  if ! test "$dry_run"; then
    "$@"
  fi
}

eval set -- "$(jq -r ".source | @sh" -- "$target/0-eaasi-mirror.json")"
for source; do

  case "$source" in
  rsync://*) ;;
  *)
    printf 'error: source "%s" not allowed\n' "$source"
    exit 1
    ;;
  esac

  _not_dry screen -dmS "$(basename -- "$0")-$(basename -- "$target")" -- sh -c 'rsync --size-only -v -r -- "$0" "$1"; sh' "$source" "$target"

done
